### PR TITLE
Enhancement/add field indicator

### PR DESCRIPTION
**Pull request by frontdevguy**
Add optional argument `fieldName` to `@stringLength` directive for better error message presentation.

Example: `password: String! @stringLength(min: 5, fieldName: "password")` would give an error `Password Length is less than 5` as opposed to `String Length is less than 5` which is confusing in some use cases.

### CODE REVIEW

**Comment by frontdevguy** [comment]
Linting passes in development but failed in CI.

**Comment by barbieri** [comment]
Hi @frontdevguy,

thanks for your contribution, but those errors are not meant to the User Interface, they are rather just hint to developers. Maybe we could make it better by using some prefix matching the failed validation.

Today it's like this, take a look:

```js
    "listLengthExample": {
      "arg": null,
      "validationErrors": [
        {
          "message": "List Length is Less than 1",
          "path": [
            "arg"
          ]
        }
      ]
    },
    "patternExample": {
      "arg": null,
      "validationErrors": [
        {
          "message": "Does not match pattern: /[a-z]+/i",
          "path": [
            "arg"
          ]
        }
      ]
    },
 ```

You should be looking at `path`, it's an array with the path of the argument that failed, in our case it's `arg` (field). It it was nested, it would look `['root', 'leaf']`. If it was an array, it would include the index.

This is per https://github.com/profusion/apollo-validation-directives/blob/master/examples/value-validation-directives.ts

If you're using the `policy: THROW`, we may need to add some extensions to identify the argument's path, but even in that case, do not map 1:1 the strings to UI (you also need to consider internationalization/localization):

```js
{
  "errors": [
    {
      "message": "List Length is Less than 1",
      "locations": [
        {
          "line": 16,
          "column": 3
        }
      ],
      "path": [
        "listLengthExample"
      ],
      "extensions": { // <-- we may need to add something here.
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ],
```

**Comment by barbieri** [comment]
see if #36 fixes it for you. Inside `errors` you get the field (mutation) and inside it you get the `extensions` object with more information, it should be `code: GRAPHQL_VALIDATION_FAILED` and a `validation` object with another path, this time to the input field (it's an array so can cope with nesting and arrays).

You can get the directive name with `extensions.validation.properties.directive`. If you create your own validation directive without the `createValidateDirectiveVisitor()` helper, then you must set the `validateProperties` manually (as the test does).

**Comment by cabelitos** [comment]
Hello @frontdevguy,
please use the release 2.1.0 which is now available on NPM to use this new feature that was implemented in #36

**Comment by frontdevguy** [comment]
@cabelitos I will give update to that. Thanks

**Pull request closed without merging**
